### PR TITLE
Test the README.md examples

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Inspired by #86 

We can actually test the `README.md`! Here is a PR that implements that.

### CODE REVIEW

**Comment by souze** [comment]
Awesome, just fix the format failure and everything looks good to me :)

**Comment by souze** [comment]
[Test](https://github.com/rust-cli/rexpect/actions/runs/3310484199/jobs/5464736156) failed like:

> thread 'main' panicked at 'assertion failed: `(left == right)`
>  left: `"hello, polly!"`,
> right: `"hello, polly!hello, polly!"`', src/session.rs:12:1

I think it's #70 again :(

**Review by souze — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
:angry: 

Maybe we can

bors try

and see what happens.

**Comment by matthiasbeyer** [comment]
The re-run of this PRs CI worked, the `try` did not.
I hate these kind of errors.

**Comment by matthiasbeyer** [comment]
Lets try again.

bors try

**Comment by matthiasbeyer** [comment]
bors merge

**Pull request merged**
