### PR TITLE
Fix sporadic test failure

### LINKED ISSUE #70: test_read_line fails randomly
I was unable to reproduce the issue on my own. So far the only time it showed up is in https://github.com/philippkeller/rexpect/actions/runs/3060626462/jobs/4939368842, for PR https://github.com/philippkeller/rexpect/pull/47.

I've reviewed the code involved in this test, but there was nothing obvious that could lead to such an issue. What I expected was that there's some sort of race condition where `Session::read_line` starts reading before the `\n` is available, and so it ends up reading the string once, stopping because it can't match and then reading again, but `NBReader` looks like it would correctly accumulate characters into the buffer and the whole operation is retried until the match is found in the buffer.

```
---- session::tests::test_read_line stdout ----
thread 'session::tests::test_read_line' panicked at 'assertion failed: `(left == right)`
  left: `"hans"`,
 right: `"hanshans"`', src/session.rs:438:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ```

### PR DESCRIPTION
**Pull request by matthiasbeyer**
<details>
Closes #70
</details>

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
So that made it work for now. @petreeftime what do you think? Is that enough? Or just a "sporadic success"? :laughing:

**Comment by matthiasbeyer** [comment]
I guess I can 

bors try

to see whether this does the trick or fails again...

**Comment by petreeftime** [comment]
The error seems to be caused by duplication of output, so I don't know whether this will help. I don't see a reason not to try, but I think there must be something that either was always buggy and interacts poorly with the test env, or caused by some minor change in nix 0.25 vs 0.14 that interacts poorly with the test env.

**Comment by petreeftime** [comment]
bors merge

**Comment by matthiasbeyer** [comment]
What I can think of is that the timeout is too short, and that caused the test to execute the following:

```console
cat 
hans
hans: no such command
```

or something like that (because `cat` gets stopped too soon). I don't know for sure, of course, but that's the first thing I could think of.

**Comment by matthiasbeyer** [comment]
Why does this take so long? Is bors overloaded right now? Weird... :thinking:

**Review by petreeftime — APPROVED** [review]

**Pull request merged**
