### PR TITLE
Remove sporadicly failing test

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is obviously not how it is done. This patch will be merged to master so that we can work on master without issues, but a PR will be filed to revert this patch immediately... with a fix, if someone can come up with one.

---

This currently blocks the 0.6.0 release. I know that this is not how it is done, but I don't see a better way.

### CODE REVIEW

**Review by petreeftime — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
bors merge=petreeftime

**Comment by petreeftime** [comment]
I think the issue might be due to some shared resource between tests. All tests execute on their own thread inside a single program and their order of execution is not guaranteed, so I think order of execution of tests or some sort of race condition might play a role in the observed bug.

**Comment by matthiasbeyer** [comment]
Hm... but the tests execute subprocesses and read and write their stdin/stdout... I don't see where are shared resources, tbh.

**Comment by petreeftime** [comment]
https://github.com/rust-cli/rexpect/blob/59213cdb11c8308daed5c2f5ecbe11db843ad71f/src/process.rs#L89

On the call to posix_openpt, I wonder if the `NO_CTTY` flag might be required, the docs seem to imply it changes the master for the calling process.

**Comment by petreeftime** [comment]
I've tested this and it seems to pass tests on my repo.

**Comment by petreeftime** [comment]
Let me create a PR for the fix.

**Comment by petreeftime** [comment]
Attempted fix in https://github.com/rust-cli/rexpect/pull/101

**Review by souze — APPROVED** [review]
This approach has my blessing. But it seems like more tests have the issue.

**Comment by matthiasbeyer** [comment]
Rebased to latest master, to see what's happening.

**Comment by matthiasbeyer** [comment]
bors try

**Pull request closed without merging**
