### PR TITLE
Prevent file descriptor leak in the spawned child.

### PR DESCRIPTION
**Pull request by kosayoda**
## Problem
After [forking the child process](https://github.com/rust-cli/rexpect/blob/cee87fc7a2ef743f09e1e880c8cf7b268a59b351/src/process.rs#L98), the file descriptors for the master and slave aren't closed since we created these descriptors ourselves (Rust sets CLOEXEC on any fds created in the stdlib).

I stumbled upon the problem when my child became a orphan after sending SIGINT to its parent. Since the drop handlers weren't run, the child isn't terminated/waited on. The expected scenario (what pexpect does) is that the master side of the pty is closed by the kernel on process exit, and SIGHUP is sent to the child process (which kills the child by default). However, since the controlling terminal is left open by the child, SIGHUP is not sent.

## Reproduction and Fix
```rust
use rexpect::spawn;

fn main() {
    let mut p = spawn("sleep 100", Some(30_000)).unwrap();

    // Hang parent
    let mut s = String::new();
    std::io::stdin().read_line(&mut s).unwrap();
}
```

On the current master:
image

On the PR branch:
image

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Nice catch, thanks!

**Comment by matthiasbeyer** [comment]
I approved CI, but as I am currently on vacation, and because of manners (:laughing:) I would like my co-maintainers to review this as well and thus I am not merging immediately.

**Review by souze — APPROVED** [review]
Looks good to me :)

**Comment by souze** [comment]
But you need to drop the trailing "." from your commit message heading for CI to pass.
Then there is a failing test. It looks like our flaky test scenario, so might work if we retry

**Comment by kosayoda** [comment]
> But you need to drop the trailing "." from your commit message heading for CI to pass.
> Then there is a failing test. It looks like our flaky test scenario, so might work if we retry

Done! Thanks for pointing that out.

**Comment by matthiasbeyer** [comment]
bors merge

**Comment by matthiasbeyer** [comment]
@souze should we release this patch as a patch release? If yes, the merge commit from master, or a dedicated `release-0.5.x` branch with only the patch from this PR?

**Pull request merged**
